Map<String, List<String>?> nullableMap = {
  "customizationColors!": [],
  "customizationFonts!": [],
  "customizationImages!": [],
  "outputImageCrop": ["size"],
  "outputImageParams!": [],
  "imageQualityCharacteristic": ["customRange", "color"],
  "detectFacesAttributeResult!": ["attribute"],
  "detectFaceResult!": ["isQualityCompliant"],
  "detectFacesConfig!": ["onlyCentralFace"],
  "detectFacesRequest": ["tag"],
  "detectFacesException": ["underlyingError"],
  "detectFacesResponse!": [],
  "faceCaptureConfig": [
    "cameraPositionAndroid",
    "timeout",
    "holdStillDuration"
  ],
  "faceCaptureResponse!": [],
  "faceSDKVersion!": [],
  "initException": ["underlyingError"],
  "livenessConfig": ["cameraPositionAndroid", "tag"],
  "livenessResponse!": ["liveness"],
  "livenessException": ["underlyingError"],
  "livenessNotification": ["response"],
  "matchFacesRequest!": ["images"],
  "matchFacesDetectionFace": ["rotationAngle", "originalRect", "crop"],
  "matchFacesDetection": ["error"],
  "matchFacesException": ["underlyingError"],
  "comparedFace": ["faceIndex", "face"],
  "comparedFacesPair": ["error"],
  "matchFacesResponse": ["tag", "error"],
  "editGroupPersonsRequest!": [],
  "person": ["metadata"],
  "personGroup": ["metadata"],
  "searchPersonRequest!": ["imageUpload", "detectAll"],
};
