name: flutter_face_api_example
description: Demonstrates how to use the flutter_face_api plugin.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.13.0
  flutter: '>=3.47.0'

dependencies:
  path_provider: ^2.1.6
  image_picker: ^1.2.3
  flutter:
    sdk: flutter
  flutter_face_api:
    path: ../
  flutter_face_core_basic: 8.4.742-rc

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.1.0

flutter:
  assets:
    - assets/
    - assets/images/
  uses-material-design: true
